'use strict';
(()=>{
const $=id=>document.getElementById(id);const PAGE_SIZE=20;let supabase=null,user=null,words=[],mode='mc',quiz=[],quizIndex=0,current=null,answered=false,session={correct:0,wrong:0,points:0},total={correct:0,wrong:0,points:0,stars:0,quizzes:0},wordPage=1,history=[];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
// NFC preserves Turkish letters; locale-aware lowercase handles I/İ/ı/i correctly.
const norm=s=>String(s??'').normalize('NFC').trim().toLocaleLowerCase('tr-TR').normalize('NFC').replace(/[.,!?;:]+$/,'');
const say=(id,msg,cls='')=>{const el=$(id);if(el){el.textContent=msg;el.className='status '+cls}};
const shuffle=a=>{const x=[...a];for(let i=x.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[x[i],x[j]]=[x[j],x[i]]}return x};
function configured(){const c=window.KELIME_KUTUM_CONFIG||{};return c.SUPABASE_URL&&c.SUPABASE_ANON_KEY&&!c.SUPABASE_URL.includes('_BURAYA')&&!c.SUPABASE_ANON_KEY.includes('_BURAYA')}
async function init(){if(!window.supabase||!configured()){$('connection-status').textContent='Kurulum gerekli';say('auth-message','Üyelik sistemini açmak için config.js dosyasına Supabase proje adresi ve anon key girilmelidir. README dosyasındaki kurulum adımlarını izleyin.','danger');$('login-btn').disabled=true;$('signup-btn').disabled=true;$('reset-btn').disabled=true;return}const c=window.KELIME_KUTUM_CONFIG;supabase=window.supabase.createClient(c.SUPABASE_URL,c.SUPABASE_ANON_KEY);$('connection-status').textContent='Çevrim içi';const {data:{session:s}}=await supabase.auth.getSession();if(s?.user)await onLogin(s.user);supabase.auth.onAuthStateChange((event,sess)=>{setTimeout(async()=>{if(sess?.user&&!user)await onLogin(sess.user);else if(!sess?.user&&user)showAuth()},0)});}
function showAuth(){user=null;words=[];history=[];$('auth-view').classList.remove('hidden');$('main-view').classList.add('hidden');$('profile-email').textContent='';}
async function onLogin(u){user=u;$('auth-view').classList.add('hidden');$('main-view').classList.remove('hidden');$('profile-email').textContent=u.email||'Hesabım';$('connection-status').textContent='Hesap eşitlendi';say('auth-message','');await loadWords();await loadHistory();stats();renderWords();renderProfile();resetQuestion()}
async function login(){const email=$('auth-email').value.trim(),password=$('auth-password').value;if(!email||!password){say('auth-message','E-posta ve şifre alanlarını doldur.','danger');return}busyAuth(true);const {data,error}=await supabase.auth.signInWithPassword({email,password});busyAuth(false);if(error)say('auth-message',friendly(error.message),'danger');else if(data.user)await onLogin(data.user)}
async function signup(){const email=$('auth-email').value.trim(),password=$('auth-password').value;if(!email||password.length<6){say('auth-message','Geçerli bir e-posta ve en az 6 karakterli şifre gir.','danger');return}busyAuth(true);const {data,error}=await supabase.auth.signUp({email,password});busyAuth(false);if(error)say('auth-message',friendly(error.message),'danger');else if(data.session&&data.user)await onLogin(data.user);else say('auth-message','Kayıt oluşturuldu. E-postana gelen doğrulama bağlantısına tıkla, ardından giriş yap.','good')}
function busyAuth(v){['login-btn','signup-btn','reset-btn'].forEach(id=>$(id).disabled=v)}
function friendly(m){if(/Invalid login credentials/i.test(m))return'E-posta veya şifre hatalı.';if(/already registered/i.test(m))return'Bu e-posta ile zaten hesap var. Giriş yapmayı dene.';if(/Email not confirmed/i.test(m))return'E-posta adresini doğrulaman gerekiyor.';return m}
async function resetPassword(){const email=$('auth-email').value.trim();if(!email){say('auth-message','Önce e-posta adresini yaz.','danger');return}const {error}=await supabase.auth.resetPasswordForEmail(email,{redirectTo:location.origin+location.pathname});say('auth-message',error?friendly(error.message):'Şifre sıfırlama bağlantısı e-posta adresine gönderildi.',error?'danger':'good')}
async function logout(){await supabase.auth.signOut();showAuth()}
async function loadWords(){const {data,error}=await supabase.from('user_words').select('*').order('created_at',{ascending:true});if(error){say('auth-message','Kelime verileri alınamadı: '+error.message,'danger');return}words=(data||[]).map(r=>({id:r.id,en:r.english,tr:r.turkish,ex:r.example||'',known:!!r.learned}));}
async function loadHistory(){const {data,error}=await supabase.from('quiz_results').select('*').order('completed_at',{ascending:false}).limit(50);if(error){console.warn(error);history=[];return}history=data||[];total=history.reduce((a,r)=>({correct:a.correct+(r.correct_count||0),wrong:a.wrong+(r.wrong_count||0),points:a.points+(r.score||0),stars:a.stars+(r.stars_awarded||0),quizzes:a.quizzes+1}),{correct:0,wrong:0,points:0,stars:0,quizzes:0})}
function stats(){ $('stat-total').textContent=words.length;$('stat-known').textContent=words.filter(w=>w.known).length;$('stat-points').textContent=total.points;$('stat-rate').textContent=(total.correct+total.wrong)?Math.round(total.correct/(total.correct+total.wrong)*100)+'%':'—';$('star-count').textContent=total.stars;$('q-score').textContent=`${session.correct} doğru · ${session.wrong} yanlış · ${session.points} puan`;}
async function add(en,tr,ex=''){en=String(en??'').normalize('NFC').trim();tr=String(tr??'').normalize('NFC').trim();ex=String(ex??'').normalize('NFC').trim();if(!en||!tr)return {ok:false,reason:'İngilizce ve Türkçe alanlarını doldur.'};if(words.some(w=>norm(w.en)===norm(en)&&norm(w.tr)===norm(tr)))return {ok:false,reason:'Bu kelime çifti zaten listede.'};const {data,error}=await supabase.from('user_words').insert({user_id:user.id,english:en,turkish:tr,example:ex,learned:false}).select().single();if(error)return {ok:false,reason:error.message};words.push({id:data.id,en:data.english,tr:data.turkish,ex:data.example||'',known:false});return {ok:true}}
function renderWords(){const q=norm($('word-search').value);const list=words.filter(w=>norm(w.en+' '+w.tr+' '+w.ex).includes(q));const pages=Math.max(1,Math.ceil(list.length/PAGE_SIZE));wordPage=Math.min(Math.max(1,wordPage),pages);const shown=list.slice((wordPage-1)*PAGE_SIZE,wordPage*PAGE_SIZE);$('word-list').innerHTML=shown.length?shown.map(w=>`<div class="word"><div class="word-main"><div class="word-en">${esc(w.en)} <span class="word-tr">— ${esc(w.tr)}</span></div>${w.ex?`<div class="muted">${esc(w.ex)}</div>`:''}<div class="muted">${w.known?'✓ Öğrenildi':'Tekrar edilebilir'}</div></div><button class="btn small" data-known="${w.id}">${w.known?'Geri al':'Öğrendim'}</button><button class="btn small" data-delete="${w.id}" aria-label="Sil">×</button></div>`).join(''):'<p class="muted">Aramana uygun kelime bulunamadı. Yeni kelime ekleyebilir veya dosya aktarabilirsin.</p>';$('page-info').textContent=`Sayfa ${wordPage} / ${pages} · ${list.length} kelime`;$('prev-page').disabled=wordPage<=1;$('next-page').disabled=wordPage>=pages;stats()}
function tab(t){document.querySelectorAll('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===t));['quiz','words','import','profile'].forEach(k=>$('view-'+k).classList.toggle('hidden',k!==t));if(t==='words')renderWords();if(t==='profile')renderProfile()}
document.querySelectorAll('[data-tab]').forEach(b=>b.addEventListener('click',()=>tab(b.dataset.tab)));document.querySelectorAll('[data-mode]').forEach(b=>b.addEventListener('click',()=>{mode=b.dataset.mode;document.querySelectorAll('[data-mode]').forEach(x=>x.classList.toggle('selected',x===b));resetQuestion()}));
function resetQuestion(){quiz=[];quizIndex=0;current=null;answered=false;$('q-word').textContent='Quize başla';$('q-label').textContent='Her quiz 20 soru içerir';$('q-example').textContent='';$('q-choices').innerHTML='';$('q-writing').classList.add('hidden');$('q-choices').classList.remove('hidden');$('q-feedback').textContent='';$('q-progress').textContent='Hazır olduğunda başla';$('next-question').disabled=true;$('start-quiz').disabled=false;$('start-quiz').textContent='20 soruluk quize başla';}
function start(){if(words.length<20){$('q-feedback').textContent=`20 soruluk quiz için en az 20 kelime gerekli. Şu anda ${words.length} kelimen var.`;$('q-feedback').className='feedback danger';return}quiz=shuffle(words).slice(0,20);quizIndex=0;session={correct:0,wrong:0,points:0};$('start-quiz').disabled=true;showQuestion();stats()}
function showQuestion(){current=quiz[quizIndex];answered=false;const dir=$('direction').value,question=dir==='en-tr'?current.en:current.tr,answer=dir==='en-tr'?current.tr:current.en;$('q-word').textContent=question;$('q-label').textContent=dir==='en-tr'?'Türkçe anlamını bul':'İngilizce karşılığını bul';$('q-example').textContent=current.ex||'';$('q-feedback').textContent='';$('q-feedback').className='feedback';$('q-progress').textContent=`Soru ${quizIndex+1} / 20`;$('next-question').disabled=true;$('next-question').textContent=quizIndex===19?'Quizi tamamla':'Sonraki soru →';$('q-choices').innerHTML='';$('q-writing').classList.toggle('hidden',mode!=='write');$('q-choices').classList.toggle('hidden',mode!=='mc');if(mode==='write'){$('q-answer').value='';$('q-answer').disabled=false;$('check-answer').disabled=false;$('q-answer').focus()}else{const options=[answer,...shuffle(words.filter(w=>w.id!==current.id)).map(w=>dir==='en-tr'?w.tr:w.en).filter(x=>norm(x)!==norm(answer))];const unique=[];options.forEach(x=>{if(!unique.some(y=>norm(y)===norm(x)))unique.push(x)});shuffle(unique.slice(0,4)).forEach(opt=>{const b=document.createElement('button');b.className='choice';b.textContent=opt;b.addEventListener('click',()=>check(opt,answer,b));$('q-choices').appendChild(b)})}}
async function check(given,answer,button){if(answered)return;answered=true;const ok=norm(given)===norm(answer);if(ok){session.correct++;session.points+=5;current.known=true;$('q-feedback').textContent='✓ Doğru cevap! +5 puan';$('q-feedback').className='feedback good'}else{session.wrong++;current.known=false;$('q-feedback').textContent='✗ Doğru cevap: '+answer;$('q-feedback').className='feedback danger'}if(button){button.style.borderColor=ok?'#16803d':'#bd3030';button.style.background=ok?'#e9f8ef':'#fff0f0'}document.querySelectorAll('#q-choices button').forEach(b=>{b.disabled=true;if(norm(b.textContent)===norm(answer)){b.style.borderColor='#16803d';b.style.background='#e9f8ef'}});$('q-answer').disabled=true;$('check-answer').disabled=true;$('next-question').disabled=false;stats();const {error}=await supabase.from('user_words').update({learned:current.known}).eq('id',current.id);if(error)console.warn('Kelime durumu güncellenemedi',error)}
async function next(){if(!answered)return;if(quizIndex<19){quizIndex++;showQuestion();return}await finishQuiz()}
async function finishQuiz(){ $('next-question').disabled=true;$('q-feedback').textContent='Quiz kaydediliyor…';const {data,error}=await supabase.from('quiz_results').insert({user_id:user.id,correct_count:session.correct,wrong_count:session.wrong,score:session.points,stars_awarded:1,question_count:20}).select().single();if(error){$('q-feedback').textContent='Quiz tamamlandı fakat kaydedilemedi: '+error.message;$('next-question').disabled=false;return}total.points+=session.points;total.correct+=session.correct;total.wrong+=session.wrong;total.stars+=1;total.quizzes+=1;history.unshift(data);$('q-progress').textContent='Quiz tamamlandı!';$('q-word').textContent='Tebrikler! ⭐';$('q-label').textContent='20 soru tamamlandı';$('q-example').textContent='';$('q-choices').innerHTML='';$('q-writing').classList.add('hidden');$('q-feedback').textContent=`${session.correct}/20 doğru · ${session.points} puan · +1 yıldız kazandın!`;$('q-feedback').className='feedback good';$('start-quiz').disabled=false;$('start-quiz').textContent='Yeni quiz başlat';$('next-question').textContent='Quiz tamamlandı';$('next-question').disabled=true;stats();renderProfile()}
$('check-answer').addEventListener('click',()=>{if(current)check($('q-answer').value,$('direction').value==='en-tr'?current.tr:current.en)});$('q-answer').addEventListener('keydown',e=>{if(e.key==='Enter'&&!answered)$('check-answer').click()});$('start-quiz').addEventListener('click',start);$('next-question').addEventListener('click',next);$('direction').addEventListener('change',resetQuestion);
$('add-word').addEventListener('click',async()=>{const b=$('add-word');b.disabled=true;const r=await add($('new-en').value,$('new-tr').value,$('new-ex').value);b.disabled=false;if(r.ok){['new-en','new-tr','new-ex'].forEach(id=>$(id).value='');wordPage=Math.max(1,Math.ceil(words.length/PAGE_SIZE));renderWords()}else alert(r.reason)});$('word-search').addEventListener('input',()=>{wordPage=1;renderWords()});$('prev-page').addEventListener('click',()=>{wordPage--;renderWords()});$('next-page').addEventListener('click',()=>{wordPage++;renderWords()});
$('word-list').addEventListener('click',async e=>{const k=e.target.closest('[data-known]'),d=e.target.closest('[data-delete]');if(k){const w=words.find(w=>w.id===k.dataset.known);if(w){w.known=!w.known;const {error}=await supabase.from('user_words').update({learned:w.known}).eq('id',w.id);if(error)alert(error.message);renderWords()}}if(d&&confirm('Bu kelime silinsin mi?')){const id=d.dataset.delete;const {error}=await supabase.from('user_words').delete().eq('id',id);if(error){alert(error.message);return}words=words.filter(w=>w.id!==id);renderWords();resetQuestion()}});
$('clear-words').addEventListener('click',async()=>{if(confirm('Hesabındaki tüm kelimeler silinsin mi? Bu işlem geri alınamaz.')){const {error}=await supabase.from('user_words').delete().eq('user_id',user.id);if(error)alert(error.message);else{words=[];wordPage=1;renderWords();resetQuestion()}}});
function parseCSV(s){s=s.replace(/^\uFEFF/,'').replace(/\0/g,'');const firstLine=(s.split(/\r?\n/,1)[0]||'');const counts={',':(firstLine.match(/,/g)||[]).length,';':(firstLine.match(/;/g)||[]).length,'\t':(firstLine.match(/\t/g)||[]).length};const delim=Object.keys(counts).sort((a,b)=>counts[b]-counts[a])[0];let rows=[],row=[],field='',quoted=false;for(let i=0;i<s.length;i++){const c=s[i];if(quoted){if(c==='"'&&s[i+1]==='"'){field+='"';i++}else if(c==='"')quoted=false;else field+=c}else if(c==='"')quoted=true;else if(c===delim){row.push(field);field=''}else if(c==='\n'||c==='\r'){if(c==='\r'&&s[i+1]==='\n')i++;row.push(field);if(row.some(v=>v.trim()))rows.push(row);row=[];field=''}else field+=c}row.push(field);if(row.some(v=>v.trim()))rows.push(row);return rows}
async function decodeFile(file){const buf=await file.arrayBuffer(),u=new Uint8Array(buf);if(u[0]===0xFF&&u[1]===0xFE)return new TextDecoder('utf-16le').decode(buf);if(u[0]===0xFE&&u[1]===0xFF)return new TextDecoder('utf-16be').decode(buf);try{return new TextDecoder('utf-8',{fatal:true}).decode(buf)}catch{try{return new TextDecoder('windows-1254').decode(buf)}catch{return new TextDecoder('utf-8').decode(buf)}}}
const headerNorm=s=>String(s??'').normalize('NFC').trim().toLocaleLowerCase('tr-TR').normalize('NFD').replace(/[\u0300-\u036f]/g,'');
$('import-csv').addEventListener('click',async()=>{const f=$('csv-file').files[0];if(!f){$('import-result').textContent='Önce bir CSV dosyası seç.';return}const b=$('import-csv');b.disabled=true;try{let rows=parseCSV(await decodeFile(f));if(!rows.length)throw Error('Dosya boş.');const first=rows[0].map(headerNorm),enNames=['english','en','ingilizce','word','kelime'],trNames=['turkce','tr','meaning','translation','anlam'];const header=first.some(x=>enNames.includes(x))&&first.some(x=>trNames.includes(x));const ix=header?{en:first.findIndex(x=>enNames.includes(x)),tr:first.findIndex(x=>trNames.includes(x)),ex:first.findIndex(x=>['example','examplesentence','ornekcumle'].includes(x))}:{en:0,tr:1,ex:2};if(header)rows.shift();let candidates=rows.map(r=>({user_id:user.id,english:String(r[ix.en]??'').normalize('NFC').trim(),turkish:String(r[ix.tr]??'').normalize('NFC').trim(),example:String((ix.ex>=0?r[ix.ex]:r[2])??'').normalize('NFC').trim(),learned:false})).filter(r=>r.english&&r.turkish);if($('replace-list').checked){const {error}=await supabase.from('user_words').delete().eq('user_id',user.id);if(error)throw error;words=[]}let added=0;for(const row of candidates){if(words.some(w=>norm(w.en)===norm(row.english)&&norm(w.tr)===norm(row.turkish)))continue;const {data,error}=await supabase.from('user_words').insert(row).select().single();if(error)throw error;words.push({id:data.id,en:data.english,tr:data.turkish,ex:data.example||'',known:!!data.learned});added++}wordPage=1;renderWords();$('import-result').textContent=`${added} yeni kelime aktarıldı. Toplam: ${words.length}.`; }catch(e){$('import-result').textContent='Dosya aktarılamadı: '+(e.message||e)}finally{b.disabled=false;$('csv-file').value=''}});
function downloadCSV(filename,text){const blob=new Blob(['\uFEFF'+text],{type:'text/csv;charset=utf-8;'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
$('download-template').addEventListener('click',()=>downloadCSV('kelime-sablonu.csv','English;Türkçe;Example\r\nachieve;başarmak;I can achieve my goal.\r\nimprove;geliştirmek;I improve every day.\r\nreliable;güvenilir;This is a reliable source.\r\n'));
$('export-backup').addEventListener('click',()=>downloadCSV('kelime-yedegi.csv','English;Türkçe;Example;Learned\r\n'+words.map(w=>[w.en,w.tr,w.ex,w.known?'Evet':'Hayır'].map(v=>'"'+String(v??'').replace(/"/g,'""')+'"').join(';')).join('\r\n')));
function renderProfile(){if(!user)return;$('profile-detail').textContent=`Hesap: ${user.email||'—'} · Kayıt tarihi: ${user.created_at?new Date(user.created_at).toLocaleDateString('tr-TR'):'—'}`;$('profile-quizzes').textContent=total.quizzes;$('profile-stars').textContent=total.stars;$('profile-points').textContent=total.points;$('profile-correct').textContent=total.correct;$('quiz-history').innerHTML=history.length?`<table class="table"><thead><tr><th>Tarih</th><th>Doğru</th><th>Puan</th><th>Yıldız</th></tr></thead><tbody>${history.slice(0,10).map(r=>`<tr><td>${esc(new Date(r.completed_at).toLocaleString('tr-TR'))}</td><td>${r.correct_count}/20</td><td>${r.score}</td><td>⭐ ${r.stars_awarded}</td></tr>`).join('')}</tbody></table>`:'Henüz tamamlanan quiz yok.'}
$('login-btn').addEventListener('click',login);$('signup-btn').addEventListener('click',signup);$('reset-btn').addEventListener('click',resetPassword);$('logout-btn').addEventListener('click',logout);init();
})();
